server:
  port: 8081

spring:
#Database
  datasource:
    url: jdbc:mysql://${env.DB_HOST}:${env.DB_PORT}/${env.DB_NAME}
    username: ${env.DB_USER}
    password: ${env.DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: user-service

#for eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#for zipkin
management:
  tracing:
    sampling:
      probability: 1.0


